### ISSUE TITLE
Typo in readme file

### ISSUE THREAD

**Issue by SepehrCloud** [awslabs/windows-web-app-migration-assistant#1]
Step 4 in readme file says:

[Optional] Edit the settings.txt JSON file, and set the following 2 variables: (1) defaultAwsProfileFileLocation : {profile_name} (2) defaultAwsProfileName : {path_to_the_new_profile_file}

The value of these two variables seems to be mismatched. It should be:

(1) defaultAwsProfileFileLocation : {path_to_the_new_profile_file} (2) defaultAwsProfileName : {profile_name}

**Comment by MiltonRen** [comment]
Thanks for catching it! Checked in the fix.
