### ISSUE TITLE
Migration script looks for IAM role "AWSElasticBeanstalkFullAccess" which was removed

### ISSUE THREAD

**Issue by jcharlesworthuk** [awslabs/windows-web-app-migration-assistant#18]
The powershell script `MigrateIISWebsiteToElasticBeanstalk.ps1` check that your IAM user has a role with the specific name "AWSElasticBeanstalkFullAccess".  This was removed so they will not be able to add it in step 2 of the "Setting Up" guide.

The role has been replaced with AdministratorAccess-AWSElasticBeanstalk

SO question: https://stackoverflow.com/questions/67485957/awselasticbeanstalkfullaccess-provides-full-access-equivalent

**Comment by smhmhmd** [comment]
Resolved by https://github.com/awslabs/windows-web-app-migration-assistant/pull/20
